line-length = 88

exclude = [
  "doc",
  "benchmark",
]

[lint]
select = [
  "D",
  "E", "W",
  "F",
  "ARG",
  "I",
]
ignore = ["E501"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"*tests/*" = ["D", "S101"]
"__init__.py" = ["F401"]
